# Generated by Django 4.1.7 on 2023-03-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retail',
            old_name='supplier',
            new_name='provision',
        ),
    ]
